option(GBCEMU_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(GBCEMU_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(GBCEMU_ENABLE_TSAN "Enable ThreadSanitizer" OFF)

function(enable_sanitizers target)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        if(GBCEMU_ENABLE_ASAN OR GBCEMU_ENABLE_UBSAN OR GBCEMU_ENABLE_TSAN)
            message(AUTHOR_WARNING "Sanitizers were requested but are not supported by '${CMAKE_CXX_COMPILER_ID}'.")
        endif()
        return()
    endif()

    if(GBCEMU_ENABLE_TSAN AND (GBCEMU_ENABLE_ASAN OR GBCEMU_ENABLE_UBSAN))
        message(FATAL_ERROR "ThreadSanitizer cannot be combined with AddressSanitizer/UndefinedBehaviorSanitizer.")
    endif()

    set(sanitizers "")
    if(GBCEMU_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(GBCEMU_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()
    if(GBCEMU_ENABLE_TSAN)
        list(APPEND sanitizers "thread")
    endif()

    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_list)
        target_compile_options(${target} INTERFACE -fsanitize=${sanitizer_list} -fno-omit-frame-pointer)
        target_link_options(${target} INTERFACE -fsanitize=${sanitizer_list})
    endif()
endfunction()
